name: Testing
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Build page and deploy to pages branch
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout pages
        git status
        pip3 install -r requirements.txt
        python3 script.py
        git add index.html
        git status
        git commit -m "generated"
        git status
        git push -f --set-upstream origin pages