name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: pages
    - name: Build page and deploy
      run: |
        pip3 install -r requirements.txt
        python3 script.py
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add index.html
        git commit -m "generated"
        git push